/** Fixed Chromium diagnostics only; never include error text, URLs, certificates or proxy values. */
export const CARD_NAVIGATION_CODES = [
  'ERR_ABORTED',
  'ERR_FAILED',
  'ERR_TIMED_OUT',
  'ERR_NAME_NOT_RESOLVED',
  'ERR_INTERNET_DISCONNECTED',
  'ERR_CONNECTION_CLOSED',
  'ERR_CONNECTION_RESET',
  'ERR_CONNECTION_REFUSED',
  'ERR_CONNECTION_ABORTED',
  'ERR_CONNECTION_FAILED',
  'ERR_CONNECTION_TIMED_OUT',
  'ERR_ADDRESS_UNREACHABLE',
  'ERR_NETWORK_CHANGED',
  'ERR_PROXY_CONNECTION_FAILED',
  'ERR_TUNNEL_CONNECTION_FAILED',
  'ERR_NO_SUPPORTED_PROXIES',
  'ERR_MANDATORY_PROXY_CONFIGURATION_FAILED',
  'ERR_PROXY_CERTIFICATE_INVALID',
  'ERR_PROXY_AUTH_REQUESTED',
  'ERR_INVALID_AUTH_CREDENTIALS',
  'ERR_UNSUPPORTED_AUTH_SCHEME',
  'ERR_CERT_COMMON_NAME_INVALID',
  'ERR_CERT_DATE_INVALID',
  'ERR_CERT_AUTHORITY_INVALID',
  'ERR_CERT_CONTAINS_ERRORS',
  'ERR_CERT_REVOKED',
  'ERR_CERT_INVALID',
  'ERR_CERT_WEAK_SIGNATURE_ALGORITHM',
  'ERR_CERT_WEAK_KEY',
  'ERR_CERT_VALIDITY_TOO_LONG',
  'ERR_CERTIFICATE_TRANSPARENCY_REQUIRED',
  'ERR_SSL_PROTOCOL_ERROR',
  'ERR_SSL_VERSION_OR_CIPHER_MISMATCH',
  'ERR_SSL_CLIENT_AUTH_CERT_NEEDED',
  'ERR_BLOCKED_BY_CLIENT',
  'ERR_BLOCKED_BY_ADMINISTRATOR',
  'ERR_ACCESS_DENIED',
  'ERR_INVALID_URL',
  'ERR_DISALLOWED_URL_SCHEME',
  'UNKNOWN'
] as const
export const CARD_NAVIGATION_CATEGORIES = [
  'aborted',
  'tls',
  'proxy',
  'authentication',
  'dns',
  'connection',
  'timeout',
  'blocked',
  'unknown'
] as const
export type CardNavigationFailure = {
  code: (typeof CARD_NAVIGATION_CODES)[number]
  category: (typeof CARD_NAVIGATION_CATEGORIES)[number]
}
